# Generated by Django 3.2.7 on 2022-02-12 03:29

from django.db import migrations, models
import home.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_folder_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='file',
            field=models.FileField(upload_to=home.models.get_upload_path),
        ),
        migrations.AlterField(
            model_name='folder',
            name='uid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
